AWSTemplateFormatVersion: '2010-09-09'
Description: "TEST: S3 bucket"

Resources:
  # S3 Bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: spring-pet-assets2
      Tags:
        - Key: Name
          Value: SpringPetAssets2Bucket

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: "arn:aws:s3:::spring-pet-assets2/*"

